@startuml
title CreateCommand Sequence Diagram

actor User
participant ":MediStock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":CreateCommand" as CreateCommand
participant ":Inventory" as Inventory

User -> App : run "create n/... u/... min/..."
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand(input)
activate Parser
create CreateCommand
Parser -> CreateCommand : new CreateCommand(...)
Parser --> App : createCommand
deactivate Parser

App -> CreateCommand : execute(inventory, ui)
activate CreateCommand

CreateCommand -> CreateCommand : create InventoryItem(...)
CreateCommand -> Inventory : addItem(item)
activate Inventory
Inventory -> Inventory : check duplicate name\nand add item
Inventory --> CreateCommand
deactivate Inventory

CreateCommand -> Ui : printCreate(...)
activate Ui
Ui --> CreateCommand
deactivate Ui

CreateCommand -> CreateCommand : histories.add(...)
CreateCommand --> App
deactivate CreateCommand

ref over App
    Local Storage Saving
end
deactivate App
@enduml
