@startuml
title DeleteCommandIndex Sequence Diagram

actor User
participant ":MediStock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":DeleteCommandIndex" as DeleteCommandIndex
participant ":Inventory" as Inventory

User -> App : run "delete i/<index>"
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand(input:String)
activate Parser

create DeleteCommandIndex
Parser -> DeleteCommandIndex : new DeleteCommandIndex(index:int)
activate DeleteCommandIndex
DeleteCommandIndex --> Parser : command:DeleteCommandIndex
deactivate DeleteCommandIndex

Parser --> App : command:DeleteCommandIndex
deactivate Parser

App -> DeleteCommandIndex : execute(inventory, ui)
activate DeleteCommandIndex

DeleteCommandIndex -> Inventory : deleteItem(index:int)
activate Inventory

loop for key in keys
    alt i == index - 1
        Inventory --> DeleteCommandIndex : deletedItem : InventoryItem
        deactivate Inventory
    end
end


DeleteCommandIndex -> Ui : printDelete(deletedItem:InventoryItem)
activate Ui
Ui --> DeleteCommandIndex : return
deactivate Ui

DeleteCommandIndex --> App : return
deactivate DeleteCommandIndex
ref over App
    Local Storage Saving
end

deactivate App
@enduml