@startuml
title DeleteCommandName Sequence Diagram

actor User
participant ":MediStock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":DeleteCommandName" as DeleteCommandName
participant ":Inventory" as Inventory

User -> App : run "delete n/<name>"
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand(input: String)
activate Parser

create DeleteCommandName
Parser -> DeleteCommandName : new DeleteCommandName(name: String)
activate DeleteCommandName
DeleteCommandName --> Parser : command: DeleteCommandName
deactivate DeleteCommandName

Parser --> App : command:DeleteCommandName
deactivate Parser

App -> DeleteCommandName : execute(inventory, ui)
activate DeleteCommandName

DeleteCommandName -> Inventory : deleteItem(name: String)
activate Inventory

Inventory --> DeleteCommandName : deletedItem: InventoryItem
deactivate Inventory

DeleteCommandName -> Ui : printDelete(deletedItem: InventoryItem)
activate Ui
Ui --> DeleteCommandName : return
deactivate Ui

DeleteCommandName --> App : return
deactivate DeleteCommandName

ref over App
    Local Storage Saving
end
deactivate App
@enduml