@startuml
title EditCommand Sequence Diagram

actor User
participant ":Medistock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":EditCommand" as EditCommand
participant ":Inventory" as Inventory

User -> App : run "edit o/... [n/...] [u/...] [min/...]"
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand(input)
activate Parser
create EditCommand
Parser -> EditCommand : new EditCommand(...)
Parser --> App : editCommand
deactivate Parser

App -> EditCommand : execute(inventory, ui)
activate EditCommand

EditCommand -> Inventory : editItem(...)
activate Inventory
Inventory -> Inventory : create updated item\nand replace old entry
Inventory --> EditCommand : updatedItem
deactivate Inventory

EditCommand -> Ui : printEdit(...)
activate Ui
Ui --> EditCommand
deactivate Ui

EditCommand -> EditCommand : histories.add(...)
EditCommand --> App
deactivate EditCommand

ref over App
    Local Storage Saving
end
deactivate App
@enduml
