@startuml
title ExitCommand Sequence Diagram

actor User
participant ":MediStock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":ExitCommand" as ExitCommand


User -> App : run "exit"
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand("exit")
activate Parser
Parser --> App : new ExitCommand()
deactivate Parser

App -> ExitCommand : execute(inventory, ui)
activate ExitCommand
ExitCommand -> Ui : printExitMessage()
activate Ui
Ui --> ExitCommand : return
deactivate Ui
ExitCommand --> App : isRunning=false
deactivate ExitCommand

App -> App : exit()
activate App

deactivate App
App -> System : System.exit(0)


deactivate App
@enduml
