@startuml
title HelpCommand Sequence Diagram

actor User
participant ":MediStock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":HelpCommand" as HelpCommand

User -> App : run "help"
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand("help")
activate Parser
Parser --> App : new HelpCommand()
deactivate Parser

App -> HelpCommand : execute(inventory, ui)
activate HelpCommand

HelpCommand -> Ui : printCommandList()
activate Ui
Ui --> HelpCommand : return
deactivate Ui

HelpCommand --> App : return
deactivate HelpCommand

deactivate App
@enduml
