@startuml
title ListCommand Sequence Diagram

actor User
participant ":MediStock" as App
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":ListCommand" as ListCommand
participant ":Inventory" as Inventory

User -> App : enters list
activate App
ref over App, Ui
    Get Input Sequence
end

App -> Parser : parseCommand(input)
activate Parser

create ListCommand
Parser -> ListCommand : new ListCommand()
activate ListCommand
ListCommand --> Parser : command:ListCommand
deactivate ListCommand

Parser --> App : command:ListCommand
deactivate Parser

App -> ListCommand : execute(...)
activate ListCommand

ListCommand -> Ui : showInventoryList(...)
activate Ui

Ui -> Inventory : getActiveBatches()
activate Inventory
Inventory --> Ui : activeItems
deactivate Inventory

Ui -> Inventory : getExpiredBatches()
activate Inventory
Inventory --> Ui : expiredItems
deactivate Inventory

alt inventory is empty
    Ui -> Ui : show empty inventory message
else inventory has items
    Ui -> Ui : display active items
    Ui -> Ui : display expired items
end

deactivate Ui
ListCommand --> App : return
deactivate ListCommand

deactivate App

@enduml